const x =10

if(!Number.isInteger(x)){
    throw new Error("x não é um número inteiro")
}

console.log('continuando o codigo.. ')

// O throw é uma forma de lançar um erro no código
// Ele é usado para parar a execução do código
// E exibir uma mensagem de erro
// O throw é usado em conjunto com o try catch
// O try catch é usado para tratar o erro lançado pelo throw
// O try é o bloco de código que pode lançar um erro
// O catch é o bloco de código que trata o erro lançado
// O erro é uma instância da classe Error
// O erro é uma forma de representar um erro no código
// O erro é uma forma de exibir uma mensagem de erro
// O erro é uma forma de parar a execução do código

