const x = 10;

try{
    x = 2
} catch (error){
    console.log(error.message)
}

// o try catch é uma forma de tratar um erro no código
// ele é usado para capturar um erro lançado pelo throw
// o try é o bloco de código que pode lançar um erro
// o catch é o bloco de código que trata o erro lançado
// o erro é uma instância da classe Error
// o erro é uma forma de representar um erro no código
